project:
  type: website
  output-dir: docs

website:
  title: "blog"
  navbar:
    right:
      - about.qmd
      - icon: bookmarks
        href: https://jvivian.github.io
      - icon: github
        href: https://github.com/jvivian
      - icon: book
        href: https://scholar.google.com/citations?user=CXQJI-AAAAAJ&hl=en&authuser=1
      - icon: linkedin
        href: https://www.linkedin.com/in/john-vivian-913b41a6/
format:
  html:
    theme: 
      light: spacelab
      dark: cyborg
    css: styles.css



