name: blog
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - plotly
  - jupyter
  - black
  - polars
  - statsmodels
  - pyarrow
  - seaborn
  - matplotlib
  - pandas
  - scipy
  - numpy
  - rich

